### ISSUE TITLE
wrong tee marked in HUD

### ISSUE THREAD

**Issue by fokkonaut** [DDNetPP/DDNetPP#190] opened 2018-10-11 20:02 UTC
sometimes not your own tee is highlighted in the HUD bottom right. if you write something to the chat or do any actions to the server your own tee will get highlighted again.
![ddnet exe screenshot 2018 10 11 - 22 01 37 65](https://user-images.githubusercontent.com/35420825/46830603-66a02480-cda1-11e8-83c0-23e989649ec8.png)
as you can see here, in the scoreboard my real tee is marked, but in the HUD bottom right its my dummy

**Comment by ChillerDragon** [comment] 2018-10-13 09:11
Is this an new DDNet++ exclusive bug? Can it be caused by the nameplates stuff you did?

**Comment by fokkonaut** [comment] 2018-10-13 10:33
just tested it, this bug is already in release 0.0.5

**Comment by ChillerDragon** [comment] 2018-10-13 18:01
You should probably make an pr in teeworlds then. Or if its fixed in 0.7 we should steal some code hehe.
But i don't know if the struggle is worth it. I guess nobody cares anyways.

**Closed** 2019-05-06 19:04 UTC
